

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-web-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - nodejs-webapi-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

networks:
  nodejs-webapi-network:
    driver: bridge
